import type { CardData } from "./types";

export const demoCurvedGalleryItems: CardData[] = [
	{
		id: "demo-01",
		title: "Nebula Notes",
		category: "Design",
		description: "UI experiments with bold type and soft motion.",
		imageUrl: "/assets/curved-gallery/demo-1.svg",
		color: "#f97316",
	},
	{
		id: "demo-02",
		title: "Spline Study",
		category: "WebGL",
		description: "A tiny exploration of curves, depth, and parallax.",
		imageUrl: "/assets/curved-gallery/demo-2.svg",
		color: "#22c55e",
	},
	{
		id: "demo-03",
		title: "Poster System",
		category: "Brand",
		description: "Modular layouts built for quick iteration.",
		imageUrl: "/assets/curved-gallery/demo-3.svg",
		color: "#06b6d4",
	},
	{
		id: "demo-04",
		title: "Type Playground",
		category: "Typography",
		description: "Heavy headlines, light details, crisp contrast.",
		imageUrl: "/assets/curved-gallery/demo-4.svg",
		color: "#a855f7",
	},
	{
		id: "demo-05",
		title: "Motion Kit",
		category: "Animation",
		description: "Springy interactions tuned for delight.",
		imageUrl: "/assets/curved-gallery/demo-5.svg",
		color: "#ef4444",
	},
	{
		id: "demo-06",
		title: "Canvas Lab",
		category: "Creative Code",
		description: "Particles, trails, and procedural textures.",
		imageUrl: "/assets/curved-gallery/demo-6.svg",
		color: "#eab308",
	},
	{
		id: "demo-07",
		title: "Grid Riffs",
		category: "Layout",
		description: "A few grid compositions for responsive systems.",
		imageUrl: "/assets/curved-gallery/demo-7.svg",
		color: "#3b82f6",
	},
	{
		id: "demo-08",
		title: "Paper Cutouts",
		category: "Illustration",
		description: "Layered shapes with a tactile vibe.",
		imageUrl: "/assets/curved-gallery/demo-8.svg",
		color: "#f43f5e",
	},
];
