// Auto-generated by vite-plugin-msdf
      export interface MSDFFontChar {
        id: number;
        index: number;
        char: string;
        width: number;
        height: number;
        xoffset: number;
        yoffset: number;
        xadvance: number;
        chnl: number;
        x: number;
        y: number;
        page: number;
      }

      export interface MSDFFontKerning {
        first: number;
        second: number;
        amount: number;
      }

      export interface MSDFFontCommon {
        lineHeight: number;
        base: number;
        scaleW: number;
        scaleH: number;
        pages: number;
        packed: number;
      }

      export interface MSDFFontDistanceField {
        fieldType: 'msdf' | 'sdf' | 'psdf';
        distanceRange: number;
      }

      export interface MSDFFontData {
        pages: string[];
        chars: MSDFFontChar[];
        common: MSDFFontCommon;
        distanceField: MSDFFontDistanceField;
        kernings?: MSDFFontKerning[];
      }

      // Font exports
      export type WaveTextData = MSDFFontData;

      declare module '//assets/msdf/*.json' {
        const fontData: MSDFFontData;
        export default fontData;
      }
